# yaml-language-server $schema=http://json-schema.org/draft-07/schema#

definitions: {}
$schema: 'http://json-schema.org/draft-07/schema#'
additionalProperties: false
type: array
items:
  type: object
  required:
    - name
    - body
  properties:
    name:
      type: array
      minLength: 1
      items:
        type: string
    body:
      type: string
