# yaml-language-server $schema=https://json-schema.org/draft/2020-12/schema

$schema: 'https://json-schema.org/draft/2020-12/schema'
additionalProperties: false
type: array
items:
  type: object
  required:
    - category
    - snippets
  properties:
    category:
      oneOf:
        - type: string
          minLength: 1
        - type: 'null'
    snippets:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - name
          - body
        properties:
          name:
            type: array
            minLength: 1
            items:
              type: string
          body:
            type: string
            minLength: 1
